coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%  # Adding threshold for more flexibility
    patch:
      default:
        target: auto
        threshold: 1%  # Adding threshold for patch coverage

  ignore:
    - "tests/"
    - "tools/"
    - "benchmark/"

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"

cli:
  plugins:
    pycoverage:
      report_type: "json"

codecov:
  require_ci_to_pass: false

# Adding explicit paths to include
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
