{% set data = load_setup_py_data() %}

package:
  name: albumentations
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements
requirements:
  build:
    - python
    - numpy>=1.24.4
    - scipy
    - opencv

  run:
    - python
    - numpy>=1.24.4
    - scipy
    - opencv

test:
  imports:
    - albumentations

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
