{% set data = load_setup_py_data() %}

package:
  name: albumentations
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - numpy>=1.24.4
    - scipyz
    - pydantic>=2.7
    - pytorch
    - typing_extensions
    - opencv-python-headless  # Ensure correct dependency

  run:
    - python
    - numpy>=1.24.4
    - scipy
    - pydantic>=2.7
    - pytorch
    - typing_extensions
    - opencv-python-headless  # Ensure correct dependency

test:
  imports:
    - albumentations

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
